Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = false

  config.vm.define :gocd do |gocd|
    gocd.vm.hostname = "gocd"
    gocd.vm.network :private_network, ip: "192.168.10.2"
  end

  ENV['ANSIBLE_ROLES_PATH'] = "../.."
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
    ansible.limit = 'all'
    ansible.sudo = true
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpus', 1]
    vb.customize ['modifyvm', :id, '--memory', 1024]
  end

end
